if(NOT TARGET nvmeservice OR NOT TARGET tutti_daemon)
  message(FATAL_ERROR "The public hardware benchmark requires gRPC/Protobuf and tutti_daemon. Refusing a stub build.")
endif()
add_executable(tutti_public_bench "${HISPARSE_PROJECT_ROOT}/src/tutti_public_bench.cpp")
target_link_libraries(tutti_public_bench PRIVATE tutti_presets CUDA::cudart)
set_target_properties(tutti_public_bench PROPERTIES CUDA_SEPARABLE_COMPILATION ON CUDA_RESOLVE_DEVICE_SYMBOLS ON LINKER_LANGUAGE CUDA RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
add_executable(gds_bench "${HISPARSE_PROJECT_ROOT}/src/gds_bench.cpp")
target_link_libraries(gds_bench PRIVATE CUDA::cudart "${CUDAToolkit_LIBRARY_DIR}/libcufile.so")
set_target_properties(gds_bench PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
add_executable(snvme_info "${HISPARSE_PROJECT_ROOT}/src/snvme_info.cpp")
target_include_directories(snvme_info PRIVATE "${CMAKE_SOURCE_DIR}/tutti/include")
set_target_properties(snvme_info PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
